/**
 * ERD Test Queries
 * Example queries to test the ERD database implementation
 * Run these in the browser console after loading erd_dummy_implementation.js
 */

// Test queries (run in console)
const testQueries = {
    // 1. Get all users
    getAllUsers: () => {
        return erdDB.getTable('Users');
    },

    // 2. Get all students with their user info
    getAllStudents: () => {
        const students = erdDB.getTable('Students');
        return students.map(s => erdDB.getStudentWithUser(s.student_id));
    },

    // 3. Get all teachers with their user info
    getAllTeachers: () => {
        const teachers = erdDB.getTable('Teachers');
        return teachers.map(t => erdDB.getTeacherWithUser(t.teacher_id));
    },

    // 4. Get all sections with course and teacher info
    getAllSections: () => {
        const sections = erdDB.getTable('Sections');
        return sections.map(s => erdDB.getSectionWithCourse(s.section_id));
    },

    // 5. Get attendance for a specific student
    getStudentAttendance: (studentId) => {
        return erdDB.getAttendanceForStudent(studentId);
    },

    // 6. Get attendance percentage for a student
    getStudentAttendancePercentage: (studentId, sectionId = null) => {
        return erdDB.calculateAttendancePercentage(studentId, sectionId);
    },

    // 7. Get all enrollments for a section
    getSectionEnrollments: (sectionId) => {
        const enrollments = erdDB.find('Enrollments', { section_id: sectionId, enrollment_status: 'Active' });
        return enrollments.map(e => {
            const student = erdDB.findOne('Students', { student_id: e.student_id });
            return { ...e, student };
        });
    },

    // 8. Get all class sessions for a section
    getSectionSessions: (sectionId) => {
        return erdDB.find('ClassSessions', { section_id: sectionId });
    },

    // 9. Get all notifications for a user
    getUserNotifications: (userId) => {
        return erdDB.find('Notifications', { user_id: userId });
    },

    // 10. Get unread notifications for a user
    getUnreadNotifications: (userId) => {
        return erdDB.find('Notifications', { user_id: userId, is_read: false });
    },

    // 11. Get all audit logs for a user
    getUserAuditLogs: (userId) => {
        return erdDB.find('AuditLogs', { user_id: userId });
    },

    // 12. Get all reports generated by a user
    getUserReports: (userId) => {
        return erdDB.find('Reports', { generated_by: userId });
    },

    // 13. Get attendance records for a session
    getSessionAttendance: (sessionId) => {
        const records = erdDB.find('AttendanceRecords', { session_id: sessionId });
        return records.map(r => {
            const student = erdDB.findOne('Students', { student_id: r.student_id });
            return { ...r, student };
        });
    },

    // 14. Get all courses
    getAllCourses: () => {
        return erdDB.getTable('Courses');
    },

    // 15. Get system settings
    getSystemSettings: () => {
        return erdDB.getTable('SystemSettings');
    },

    // 16. Get a specific setting value
    getSetting: (key) => {
        const setting = erdDB.findOne('SystemSettings', { key: key });
        return setting ? setting.value : null;
    },

    // 17. Create a new attendance record
    createAttendanceRecord: (studentId, sessionId, status, recordedBy, method = 'Manual') => {
        return erdDB.insert('AttendanceRecords', {
            student_id: studentId,
            session_id: sessionId,
            status: status,
            recorded_by: recordedBy,
            method: method
        });
    },

    // 18. Create a new notification
    createNotification: (userId, title, message, triggerType) => {
        return erdDB.insert('Notifications', {
            user_id: userId,
            title: title,
            message: message,
            is_read: false,
            trigger_type: triggerType
        });
    },

    // 19. Mark notification as read
    markNotificationRead: (notificationId) => {
        return erdDB.update('Notifications', { notification_id: notificationId }, { is_read: true });
    },

    // 20. Get attendance statistics for a section
    getSectionAttendanceStats: (sectionId) => {
        const enrollments = erdDB.find('Enrollments', { section_id: sectionId, enrollment_status: 'Active' });
        const sessions = erdDB.find('ClassSessions', { section_id: sectionId });
        
        return enrollments.map(enrollment => {
            const student = erdDB.findOne('Students', { student_id: enrollment.student_id });
            const attendance = erdDB.getAttendanceForStudent(enrollment.student_id, sectionId);
            const presentCount = attendance.filter(a => a.status === 'Present').length;
            const percentage = sessions.length > 0 ? Math.round((presentCount / sessions.length) * 100) : 0;
            
            return {
                student: student,
                totalSessions: sessions.length,
                presentCount: presentCount,
                attendancePercentage: percentage
            };
        });
    }
};

// Make test queries available globally
if (typeof window !== 'undefined') {
    window.testQueries = testQueries;
    console.log('Test queries loaded. Use testQueries to run example queries.');
    console.log('Example: testQueries.getAllUsers()');
}

